spring.application.name=social-platform-core

# PERSISTENCE CONFIGURATION
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/social_platform_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# FLYWAY CONFIGURATION
spring.flyway.baseline-on-migrate=true

# JACKSON CONFIGURATION
spring.jackson.serialization.write-dates-as-timestamps=false

# SERVER HARDENING & TRANSPORT CONFIGURATION
server.forward-headers-strategy=framework
server.compression.enabled=true

# ACTUATOR CONFIGURATION
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# SPRINGDOC CONFIGURATION
springdoc.swagger-ui.disable-swagger-default-url=true